### ISSUE TITLE
run with error

### ISSUE THREAD

**Issue by yctaii** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#14]
When I run the query, it pops up an error like "Exception: System.InvalidOperationException: Cannot start process because a file name has not been provided."

**Comment by Daydreamer-riri** [comment]
Please provide more information, such as screenshots, plugin version, powertoys version, configuration file content.

**Comment by yctaii** [comment]
powertoys version: 0.80.1.0
OS Version: Microsoft Windows NT 10.0.22621.0
IntPtr Length: 8
x64: True
Date: 2024/4/26 19:30:27
Exception:
System.InvalidOperationException: Cannot start process because a file name has not been provided.
   at System.Diagnostics.Process.Start()
   at Wox.Infrastructure.Helper.OpenInShell(String path, String arguments, String workingDir, ShellRunAsType runAs, Boolean runWithHiddenWindow)
   at Wox.Infrastructure.Helper.OpenCommandInShell(String path, String pattern, String arguments, String workingDir, ShellRunAsType runAs, Boolean runWithHiddenWindow)
   at Community.PowerToys.Run.Plugin.WebSearchShortcut.Main.OpenInBrowser(String url)
   at Community.PowerToys.Run.Plugin.WebSearchShortcut.Main.<>c__DisplayClass43_0.<GetResultForSearch>b__0(ActionContext _)
   at PowerLauncher.ViewModel.MainViewModel.<>c__DisplayClass31_0.<OpenResultsEvent>b__0()
   at System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   at System.Windows.Threading.Dispatcher.Invoke(Action callback)
   at PowerLauncher.ViewModel.MainViewModel.OpenResultsEvent(Object index, Boolean isMouseClick)
   at System.Windows.Input.CommandManager.TranslateInput(IInputElement targetElement, InputEventArgs inputEventArgs)
   at System.Windows.UIElement.OnKeyDownThunk(Object sender, KeyEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Interop.HwndKeyboardInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawKeyboardActions actions, Int32 scanCode, Boolean isExtendedKey, Boolean isSystemKey, Int32 virtualKey)
   at System.Windows.Interop.HwndKeyboardInputProvider.ProcessKeyAction(MSG& msg, Boolean& handled)
   at System.Windows.Interop.HwndSource.CriticalTranslateAccelerator(MSG& msg, ModifierKeys modifiers)
   at System.Windows.Interop.HwndSource.OnPreprocessMessage(Object param)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

Plugin version 0.5

**Comment by yctaii** [comment]
this is the content of  my config file:
{
  "Google": {
    "Url": "https://www.google.com/search?q=%s",
    "SuggestionProvider": "Google"
  },
  "Bing": {
    "Url": "https://www.bing.com/search?q=%s",
    "SuggestionProvider": "Bing"
  },
  "GitHub": {
    "Url": "https://www.github.com/search?q=%s",
    "Keyword": "gh"
  }
}

**Comment by Daydreamer-riri** [comment]
When did this error occur? Is there a screenshot? I want to determine if this is my issue or a problem with PowerToys.

**Comment by yctaii** [comment]
After pressing the enter button, an error message appears.
![1714134757934](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/95557256/a557fdf4-2e2d-4f35-9a36-8866be71d00d)
![1714134800547](https://github.com/Daydreamer-riri/PowerToys-Run-WebSearchShortcut/assets/95557256/3b413e43-cf2a-4f9a-aff0-461b216ad7c8)

**Comment by Daydreamer-riri** [comment]
This situation appears to be that the default browser is not being called correctly.

Do you have a default browser set?

Can the built-in web search plugin be used normally? The principles of the two plugins are the same when it comes to opening the browser.

**Comment by yctaii** [comment]
This could have been caused by me turning off the web search in powertoys run, I reinstalled powertoys and now everything is fine.

**Comment by janikkokot** [comment]
I encountered the exact same issue just now.
I could resolve it by running:
```
?? !reload
```

**Comment by janikkokot** [comment]
Encountered this issue again after a PC restart.
The problem seems to result from the Web Search plugin not being enabled, as already suggested by @yctaii.
After enabling the Web Search plugin it works fine again, even if the Web Search plugin is deactivated afterwards.
