### ISSUE TITLE
Unauthorized Access of the icons

### ISSUE THREAD

**Issue by agyojiawei** [Daydreamer-riri/PowerToys-Run-WebSearchShortcut#26]
Version: 0.84.1.0
OS Version: Microsoft Windows NT 10.0.22631.0
IntPtr Length: 8
x64: True
Date: 29/09/2024 18:46:52
Exception:
System.UnauthorizedAccessException: Access to the path 'C:\Program Files\PowerToys\RunPlugins\WebSearchShortcut\Images\Icons' is denied.
   at System.IO.FileSystem.CreateDirectory(String fullPath, Byte[] securityDescriptor)
   at System.IO.Directory.CreateDirectory(String path)
   at Community.PowerToys.Run.Plugin.WebSearchShortcut.Models.Item.DownLoadIcon()
   at Community.PowerToys.Run.Plugin.WebSearchShortcut.WebSearchShortcutStorage.DownLoadIcon()
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by Daydreamer-riri** [comment]
Can you provide your profile? This can help me reproduce your question.
